//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Commons.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Codes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Codes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Commons.Recursos.Codes", typeof(Codes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error, consulte a su Administrador..
        /// </summary>
        public static string ERR_00_00 {
            get {
                return ResourceManager.GetString("ERR_00_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error mientras realizaba la consulta..
        /// </summary>
        public static string ERR_00_01 {
            get {
                return ResourceManager.GetString("ERR_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error mientras registraba la información..
        /// </summary>
        public static string ERR_00_02 {
            get {
                return ResourceManager.GetString("ERR_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error mientras eliminaba la información..
        /// </summary>
        public static string ERR_00_03 {
            get {
                return ResourceManager.GetString("ERR_00_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error mientras actualizaba la información..
        /// </summary>
        public static string ERR_00_04 {
            get {
                return ResourceManager.GetString("ERR_00_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al iniciar la transacción..
        /// </summary>
        public static string ERR_00_05 {
            get {
                return ResourceManager.GetString("ERR_00_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro recibido es nulo..
        /// </summary>
        public static string ERR_00_06 {
            get {
                return ResourceManager.GetString("ERR_00_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro id es incorrecto..
        /// </summary>
        public static string ERR_00_07 {
            get {
                return ResourceManager.GetString("ERR_00_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification confidence must be a value between 0 and 2..
        /// </summary>
        public static string ERR_00_08 {
            get {
                return ResourceManager.GetString("ERR_00_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor debe ser en formato int..
        /// </summary>
        public static string ERR_00_09 {
            get {
                return ResourceManager.GetString("ERR_00_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario recibido es nulo..
        /// </summary>
        public static string ERR_00_10 {
            get {
                return ResourceManager.GetString("ERR_00_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar enviar el correo..
        /// </summary>
        public static string ERR_00_11 {
            get {
                return ResourceManager.GetString("ERR_00_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al obtener el nombre del usuario de sesión..
        /// </summary>
        public static string ERR_00_12 {
            get {
                return ResourceManager.GetString("ERR_00_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al obtener el usuario de sesión..
        /// </summary>
        public static string ERR_00_13 {
            get {
                return ResourceManager.GetString("ERR_00_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al obtener el Id del usuario de sesión..
        /// </summary>
        public static string ERR_00_14 {
            get {
                return ResourceManager.GetString("ERR_00_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al obtener el Id de perfil del usuario de sesión..
        /// </summary>
        public static string ERR_00_15 {
            get {
                return ResourceManager.GetString("ERR_00_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error mientras ejecutaba el procedimiento..
        /// </summary>
        public static string ERR_00_16 {
            get {
                return ResourceManager.GetString("ERR_00_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación exitosa..
        /// </summary>
        public static string INF_00_00 {
            get {
                return ResourceManager.GetString("INF_00_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es requerido..
        /// </summary>
        public static string REQ_00_01 {
            get {
                return ResourceManager.GetString("REQ_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no cumple con la validación..
        /// </summary>
        public static string REQ_00_02 {
            get {
                return ResourceManager.GetString("REQ_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrieron errores de validaciones de tipo SingleResponse..
        /// </summary>
        public static string SingleResponseValidations {
            get {
                return ResourceManager.GetString("SingleResponseValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single response incorrecto..
        /// </summary>
        public static string WRN_00_00 {
            get {
                return ResourceManager.GetString("WRN_00_00", resourceCulture);
            }
        }
    }
}
