//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Commons.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodesCotizador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodesCotizador() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Commons.Recursos.CodesCotizador", typeof(CodesCotizador).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay aseguradoras que soporten el Udi seleccionado..
        /// </summary>
        public static string ERR_01_01 {
            get {
                return ResourceManager.GetString("ERR_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una configuración de panel que soporte el Udi seleccionado. .
        /// </summary>
        public static string ERR_01_02 {
            get {
                return ResourceManager.GetString("ERR_01_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto seleccionado no tiene formas de pago configuradas..
        /// </summary>
        public static string ERR_01_03 {
            get {
                return ResourceManager.GetString("ERR_01_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una configuración de panel para la combinación de producto flex seleccionado..
        /// </summary>
        public static string ERR_01_04 {
            get {
                return ResourceManager.GetString("ERR_01_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar la consulta del número de clientes por perfil..
        /// </summary>
        public static string ERR_01_05 {
            get {
                return ResourceManager.GetString("ERR_01_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro en consulta cantidad cliente es null.
        /// </summary>
        public static string ERR_01_06 {
            get {
                return ResourceManager.GetString("ERR_01_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al precargar la información de cotización..
        /// </summary>
        public static string ERR_01_07 {
            get {
                return ResourceManager.GetString("ERR_01_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al verificar si existe la cobertura de daños materiales en la cotización..
        /// </summary>
        public static string ERR_01_08 {
            get {
                return ResourceManager.GetString("ERR_01_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la cobertura RC Ecológica.
        /// </summary>
        public static string ERR_01_09 {
            get {
                return ResourceManager.GetString("ERR_01_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al validar el limite &quot;Valor Factura&quot;.
        /// </summary>
        public static string ERR_01_10 {
            get {
                return ResourceManager.GetString("ERR_01_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al validar el porcentaje permitido para coberturas especiales o adaptaciones.
        /// </summary>
        public static string ERR_01_11 {
            get {
                return ResourceManager.GetString("ERR_01_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe configuración del porcentaje permitido para suma asegurada de adaptaciones y equipo especial..
        /// </summary>
        public static string ERR_01_12 {
            get {
                return ResourceManager.GetString("ERR_01_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró coincidencias en la configuración para.
        /// </summary>
        public static string INF_01_01 {
            get {
                return ResourceManager.GetString("INF_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario actual no tiene agencias configuradas.
        /// </summary>
        public static string INF_01_02 {
            get {
                return ResourceManager.GetString("INF_01_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron versiones que cumplan con los criterios seleccionados.
        /// </summary>
        public static string INF_01_03 {
            get {
                return ResourceManager.GetString("INF_01_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron pasajeros que cumplan con los criterios seleccionados.
        /// </summary>
        public static string INF_01_04 {
            get {
                return ResourceManager.GetString("INF_01_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron coincidencias en la búsqueda.
        /// </summary>
        public static string INF_01_05 {
            get {
                return ResourceManager.GetString("INF_01_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente seleccionado no cuenta con productos configurados.
        /// </summary>
        public static string INF_01_06 {
            get {
                return ResourceManager.GetString("INF_01_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta configuración de parámetros.
        /// </summary>
        public static string INF_01_07 {
            get {
                return ResourceManager.GetString("INF_01_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor capturado &quot;{{Valor}}&quot; sobrepasa el monto permitido &quot;{{Limite}}&quot;..
        /// </summary>
        public static string INF_01_08 {
            get {
                return ResourceManager.GetString("INF_01_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor capturado sobrepasa el porcentaje permitido para {{Cobertura}}.
        /// </summary>
        public static string INF_01_09 {
            get {
                return ResourceManager.GetString("INF_01_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sección de Información del Cliente es requerida..
        /// </summary>
        public static string REQ_01_00 {
            get {
                return ResourceManager.GetString("REQ_01_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sección de Datos del Vehículo es requerida..
        /// </summary>
        public static string REQ_01_01 {
            get {
                return ResourceManager.GetString("REQ_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sección de Datos de Cotización es requerida..
        /// </summary>
        public static string REQ_01_02 {
            get {
                return ResourceManager.GetString("REQ_01_02", resourceCulture);
            }
        }
    }
}
