//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Commons.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodesCalendario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodesCalendario() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Commons.Recursos.CodesCalendario", typeof(CodesCalendario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error favor de consultar a su Administrador..
        /// </summary>
        public static string ERR_07_01 {
            get {
                return ResourceManager.GetString("ERR_07_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta..
        /// </summary>
        public static string ERR_07_02 {
            get {
                return ResourceManager.GetString("ERR_07_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras registraba la información..
        /// </summary>
        public static string ERR_07_03 {
            get {
                return ResourceManager.GetString("ERR_07_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras eliminaba la información..
        /// </summary>
        public static string ERR_07_04 {
            get {
                return ResourceManager.GetString("ERR_07_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras actualizaba la información..
        /// </summary>
        public static string ERR_07_05 {
            get {
                return ResourceManager.GetString("ERR_07_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al iniciar la transacción..
        /// </summary>
        public static string ERR_07_06 {
            get {
                return ResourceManager.GetString("ERR_07_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parametro recibido es nulo..
        /// </summary>
        public static string ERR_07_07 {
            get {
                return ResourceManager.GetString("ERR_07_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parametro id es incorrecto..
        /// </summary>
        public static string ERR_07_08 {
            get {
                return ResourceManager.GetString("ERR_07_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification confidence must be a value between 0 and 2..
        /// </summary>
        public static string ERR_07_09 {
            get {
                return ResourceManager.GetString("ERR_07_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor debe ser en formato int..
        /// </summary>
        public static string ERR_07_10 {
            get {
                return ResourceManager.GetString("ERR_07_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dia Inhabil ya existe..
        /// </summary>
        public static string INF_07_00 {
            get {
                return ResourceManager.GetString("INF_07_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el día inhábil de una fecha anterior o en curso..
        /// </summary>
        public static string INF_07_01 {
            get {
                return ResourceManager.GetString("INF_07_01", resourceCulture);
            }
        }
    }
}
