//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Commons.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodesTickets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodesTickets() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Commons.Recursos.CodesTickets", typeof(CodesTickets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error favor de consultar a su Administrador..
        /// </summary>
        public static string ERR_00_01 {
            get {
                return ResourceManager.GetString("ERR_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta..
        /// </summary>
        public static string ERR_00_02 {
            get {
                return ResourceManager.GetString("ERR_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta de Tickets..
        /// </summary>
        public static string ERR_00_03 {
            get {
                return ResourceManager.GetString("ERR_00_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta de clientes al registrar nuevo Ticket..
        /// </summary>
        public static string ERR_00_04 {
            get {
                return ResourceManager.GetString("ERR_00_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta de las agencias al registrar datos de contacto para nuevo Ticket..
        /// </summary>
        public static string ERR_00_05 {
            get {
                return ResourceManager.GetString("ERR_00_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta del si el cliente es flotilla o individual para nuevo Ticket..
        /// </summary>
        public static string ERR_00_06 {
            get {
                return ResourceManager.GetString("ERR_00_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta de las caratulas en base al cliente para nuevo Ticket..
        /// </summary>
        public static string ERR_00_07 {
            get {
                return ResourceManager.GetString("ERR_00_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta del responsable en base al cliente para nuevo Ticket..
        /// </summary>
        public static string ERR_00_08 {
            get {
                return ResourceManager.GetString("ERR_00_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta de los tipos de tickets en base al cliente para nuevo Ticket..
        /// </summary>
        public static string ERR_00_09 {
            get {
                return ResourceManager.GetString("ERR_00_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta del catálogo de orígenes (reporta a) en base al cliente para nuevo Ticket..
        /// </summary>
        public static string ERR_00_10 {
            get {
                return ResourceManager.GetString("ERR_00_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras realizaba la consulta del catálogo de estatus en base al cliente para nuevo Ticket..
        /// </summary>
        public static string ERR_00_11 {
            get {
                return ResourceManager.GetString("ERR_00_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al guardar la información del Ticket..
        /// </summary>
        public static string ERR_00_12 {
            get {
                return ResourceManager.GetString("ERR_00_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al guardar el archivo asociado al Ticket..
        /// </summary>
        public static string ERR_00_13 {
            get {
                return ResourceManager.GetString("ERR_00_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al eliminar el archivo asociado al Ticket..
        /// </summary>
        public static string ERR_00_14 {
            get {
                return ResourceManager.GetString("ERR_00_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al consultar los dias inhabiles..
        /// </summary>
        public static string ERR_00_15 {
            get {
                return ResourceManager.GetString("ERR_00_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al consultar las aseguradoras por cliente..
        /// </summary>
        public static string ERR_00_16 {
            get {
                return ResourceManager.GetString("ERR_00_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al consultar las aseguradoras por cliente..
        /// </summary>
        public static string ERR_00_17 {
            get {
                return ResourceManager.GetString("ERR_00_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al consultar los datos de correo del responsable..
        /// </summary>
        public static string ERR_00_18 {
            get {
                return ResourceManager.GetString("ERR_00_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al calcular el tiempo de atencion del ticket..
        /// </summary>
        public static string ERR_00_19 {
            get {
                return ResourceManager.GetString("ERR_00_19", resourceCulture);
            }
        }
    }
}
