//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Commons.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodesEmision {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodesEmision() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Commons.Recursos.CodesEmision", typeof(CodesEmision).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar cargar los elementos..
        /// </summary>
        public static string ERR_00_00 {
            get {
                return ResourceManager.GetString("ERR_00_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar los datos de cotización..
        /// </summary>
        public static string ERR_00_01 {
            get {
                return ResourceManager.GetString("ERR_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar los datos de Incisos y Endoso.
        /// </summary>
        public static string ERR_00_02 {
            get {
                return ResourceManager.GetString("ERR_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Nacionalidad.
        /// </summary>
        public static string ERR_00_03 {
            get {
                return ResourceManager.GetString("ERR_00_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Género.
        /// </summary>
        public static string ERR_00_04 {
            get {
                return ResourceManager.GetString("ERR_00_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Paises.
        /// </summary>
        public static string ERR_00_05 {
            get {
                return ResourceManager.GetString("ERR_00_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Docto de Identificación.
        /// </summary>
        public static string ERR_00_06 {
            get {
                return ResourceManager.GetString("ERR_00_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Entidad de Nacimiento.
        /// </summary>
        public static string ERR_00_07 {
            get {
                return ResourceManager.GetString("ERR_00_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Profesión.
        /// </summary>
        public static string ERR_00_08 {
            get {
                return ResourceManager.GetString("ERR_00_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Ocupación.
        /// </summary>
        public static string ERR_00_09 {
            get {
                return ResourceManager.GetString("ERR_00_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Giro de Negocio.
        /// </summary>
        public static string ERR_00_10 {
            get {
                return ResourceManager.GetString("ERR_00_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo SiNo.
        /// </summary>
        public static string ERR_00_11 {
            get {
                return ResourceManager.GetString("ERR_00_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar el combo Regimen Fiscal Empresarial.
        /// </summary>
        public static string ERR_00_12 {
            get {
                return ResourceManager.GetString("ERR_00_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al cargar los combos.
        /// </summary>
        public static string ERR_00_13 {
            get {
                return ResourceManager.GetString("ERR_00_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al estructurar los datos de emisión.
        /// </summary>
        public static string ERR_00_14 {
            get {
                return ResourceManager.GetString("ERR_00_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al consultar las valores prima.
        /// </summary>
        public static string ERR_00_15 {
            get {
                return ResourceManager.GetString("ERR_00_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al consultar la Información del cliente.
        /// </summary>
        public static string ERR_00_16 {
            get {
                return ResourceManager.GetString("ERR_00_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al consultar la serie.
        /// </summary>
        public static string ERR_00_17 {
            get {
                return ResourceManager.GetString("ERR_00_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La serie captura ya ha sido emitida y esta vigente en la póliza .
        /// </summary>
        public static string INF_00_00 {
            get {
                return ResourceManager.GetString("INF_00_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie capturada incorrecta, debe estar compuesta de 17 caracteres.
        /// </summary>
        public static string INF_00_01 {
            get {
                return ResourceManager.GetString("INF_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie capturada incorrecta, contiene caracteres (IOQÑ,·%.$ etc.) no validos.
        /// </summary>
        public static string INF_00_02 {
            get {
                return ResourceManager.GetString("INF_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de contrato incorrecto, contiene caracteres especiales no validos.
        /// </summary>
        public static string INF_00_03 {
            get {
                return ResourceManager.GetString("INF_00_03", resourceCulture);
            }
        }
    }
}
