//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Business.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBusiness {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBusiness() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Business.Recursos.RecursosBusiness", typeof(RecursosBusiness).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propuesta de Cotización.
        /// </summary>
        internal static string AsuntoCorreo {
            get {
                return ResourceManager.GetString("AsuntoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;Estimado(a) Cliente:&lt;br&gt;
        ///Gracias por su preferencia y por la confianza que deposita en nosotros buscando proteger su patrimonio.&lt;br&gt;&lt;br&gt;
        /// 
        ///Adjunto al presente encontrar&amp;aacute; la cotizaci&amp;oacute;n en formato PDF que contiene la propuesta para asegurar su unidad, le recordamos que esta tendr&amp;aacute; una vigencia de 30 d&amp;iacute;as a partir de este momento y podr&amp;aacute; utilizarse para el veh&amp;iacute;culo y las condiciones se&amp;ntilde;aladas en el adjunto.
        /// &lt;br&gt;&lt;br&gt;
        ///Cualquier duda o comentario al respec [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CuerpoCorreo {
            get {
                return ResourceManager.GetString("CuerpoCorreo", resourceCulture);
            }
        }
    }
}
