//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM45Secure.Commons.Zero.Exceptions.Codes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZeroCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZeroCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM45Secure.Commons.Zero.Exceptions.Codes.ZeroCodes", typeof(ZeroCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede generar un insert a partir de un objeto nulo..
        /// </summary>
        public static string ERR_00_01 {
            get {
                return ResourceManager.GetString("ERR_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sentencia no tiene clausula where, favor de verificar..
        /// </summary>
        public static string ERR_00_02 {
            get {
                return ResourceManager.GetString("ERR_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar la sentencia Delete sin Where..
        /// </summary>
        public static string ERR_00_03 {
            get {
                return ResourceManager.GetString("ERR_00_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún atributo anotado con IdColumn en la entidad, favor de verificar..
        /// </summary>
        public static string ERR_00_04 {
            get {
                return ResourceManager.GetString("ERR_00_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado un mensaje por default con la clave {0}, o no se ha colocado la clave del mensaje en el Atributo..
        /// </summary>
        public static string ERR_00_05 {
            get {
                return ResourceManager.GetString("ERR_00_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQ_000_01.
        /// </summary>
        public static string MSJ_00_01 {
            get {
                return ResourceManager.GetString("MSJ_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL_000_01.
        /// </summary>
        public static string MSJ_00_02 {
            get {
                return ResourceManager.GetString("MSJ_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta de negocio nula..
        /// </summary>
        public static string WRN_00_00 {
            get {
                return ResourceManager.GetString("WRN_00_00", resourceCulture);
            }
        }
    }
}
